"""Examples 39.1.1, 39.1.2: ten repeated measurements of a wrist force sensor with a 20 N standard weight; Type A,
Type B, combined and expanded uncertainty.

The readings are generated by the program from "true value 20 N, systematic bias +0.12 N, standard deviation of the
random error 0.06 N, display resolution 0.01 N" (fixed random seed).
"""
import math

import numpy as np

from bookout import out

rng = np.random.default_rng(391)
true, bias, sd, res = 20.0, 0.12, 0.06, 0.01
x = np.round(true + bias + rng.normal(0, sd, 10), 2)
n = len(x)
mean = float(x.mean())
s = float(x.std(ddof=1))                   # experimental standard deviation (Bessel's formula)
uA = s / math.sqrt(n)                      # standard uncertainty of the mean (Type A)
uB_res = res / 2 / math.sqrt(3)            # resolution: uniform distribution of half-width 0.005 N
cal_U, cal_k = 0.10, 2                     # calibration certificate: weight and reading system together U = 0.10 N (k = 2)
uB_cal = cal_U / cal_k
uc = math.sqrt(uA ** 2 + uB_res ** 2 + uB_cal ** 2)
U = 2 * uc
err = mean - true                          # difference from the nominal value of the weight: mainly systematic error

# check: Bessel's formula agrees with the term-by-term computation
assert abs(s - math.sqrt(((x - mean) ** 2).sum() / (n - 1))) < 1e-12
# the systematic error of 0.12 N is far larger than the random uncertainty of the mean, so zero/sensitivity must be corrected
assert err > 3 * uA
assert err > U and mean - U > true           # text: the difference exceeds U; the uncorrected interval does not contain 20 N

table = r"\begin{array}{" + "c" * n + "}" + " & ".join(f"{v:.2f}" for v in x) + r"\end{array}"
out(table=table, n=n, mean=mean, s=s, uA=uA, uB_res=uB_res, uB_cal=uB_cal, uc=uc, U=U, err=err,
    lo=mean - U, hi=mean + U, x_min=float(x.min()), x_max=float(x.max()), _x=x.tolist())
