"""图 7.6.1：反函数的图像关于 y = x 对称，对应点的切线斜率互为倒数；图 7.6.2：肘关节所需角速度随肩—腕心距离 r 的变化。"""
import math

import numpy as np

from _fig import ACC, BLUE, GREEN, INK, MUTED, RED, T, clean, figure, plt
from _traj import ur5e_links

fig, ax = plt.subplots(figsize=(5.4, 5.2))
x = np.linspace(-2.2, 1.6, 300)
ax.plot(x, np.exp(x), color=BLUE, lw=2, label="$y=e^x$")
y = np.linspace(0.05, 5, 300)
ax.plot(y, np.log(y), color=RED, lw=2, label=r"$y=\ln x$")
ax.plot([-2.2, 5], [-2.2, 5], color=MUTED, ls=":", lw=1)
a = 1.0
ax.plot([a], [math.e], "o", color=BLUE, ms=6)
ax.plot([math.e], [a], "o", color=RED, ms=6)
s = np.linspace(-0.4, 0.4, 2)
ax.plot(a + s, math.e + math.e * s, color=BLUE, lw=1.4, ls="--")
ax.plot(math.e + math.e * s, a + s, color=RED, lw=1.4, ls="--")
ax.plot([a, math.e], [math.e, a], color=MUTED, lw=0.8, ls="--")
ax.text(a - 1.9, math.e + 0.15, T("斜率 e", "slope e"), color=BLUE)
ax.text(math.e + 0.1, a - 0.55, T("斜率 1/e", "slope 1/e"), color=RED)
ax.text(4.15, 3.75, "$y=x$", color=MUTED)
ax.set_aspect("equal")
ax.set_xlim(-2.2, 5)
ax.set_ylim(-2.2, 5)
ax.legend(frameon=False, loc="lower right")
clean(ax)
ax.axvline(0, color=MUTED, lw=0.6, zorder=0)
fig.tight_layout()
figure(fig, "fig7_6_1")

l1, l2 = ur5e_links()
rdot = 0.1
r = np.linspace(0.12, l1 + l2 - 1e-4, 600)
th2 = np.arccos((r**2 - l1**2 - l2**2) / (2 * l1 * l2))
w = r * rdot / (l1 * l2 * np.sin(th2))
fig, (b1, b2) = plt.subplots(1, 2, figsize=(10, 4.0), gridspec_kw={"width_ratios": [1, 1.4]})
th1 = math.radians(10)
tt2 = math.acos((0.6**2 - l1**2 - l2**2) / (2 * l1 * l2))
E = np.array([l1 * math.cos(th1), l1 * math.sin(th1)])
W = E + l2 * np.array([math.cos(th1 + tt2), math.sin(th1 + tt2)])
b1.plot([0, E[0], W[0]], [0, E[1], W[1]], color=BLUE, lw=5, alpha=0.55, solid_capstyle="round")
b1.plot([0, E[0]], [0, E[1]], "o", color="white", mec=INK, ms=8)
b1.plot([0, W[0]], [0, W[1]], color=RED, lw=1.4, ls="--")
b1.text(W[0] / 2 - 0.12, W[1] / 2 + 0.03, "$r$", color=RED, fontsize=13)
b1.text(E[0] - 0.05, E[1] - 0.09, r"$\theta_2$", fontsize=12)
b1.text(0.02, -0.08, T("肩", "shoulder"), color=MUTED)
b1.text(W[0] + 0.02, W[1], T("腕心", "wrist"), color=MUTED)
b1.set_aspect("equal")
b1.set_xlim(-0.15, 0.65)
b1.set_ylim(-0.15, 0.65)
b1.axis("off")
b2.plot(r, np.degrees(w), color=INK, lw=2)
b2.axhline(180, color=RED, ls="--", lw=1.2)
b2.axvline(l1 + l2, color=MUTED, ls=":", lw=1)
b2.text(0.15, 190, T("限速 180°/s", "limit 180°/s"), color=RED)
b2.text(l1 + l2 - 0.005, 330, T("伸直", "straight"), color=MUTED, ha="right")
b2.set_ylim(0, 360)
b2.set_xlabel(T("肩—腕心距离 r / m", "shoulder–wrist distance r / m"))
b2.set_ylabel(T("|dθ₂/dt| / (°/s)", "|dθ₂/dt| / (°/s)"))
b2.set_title(T("腕心以 0.1 m/s 向外移动时，肘关节需要的角速度", "Elbow speed needed for the wrist to move out at 0.1 m/s"), fontsize=11)
clean(b2, zero=False)
fig.tight_layout()
figure(fig, "fig7_6_2")
