"""图 7.4.1：单位圆上匀速转动的点，速度垂直于半径；图 7.4.2：2ˣ、eˣ、3ˣ 在 0 点的切线；图 7.4.3：电机转速的一阶响应。"""
import math

import numpy as np

from _fig import ACC, BLUE, GREEN, INK, MUTED, RED, T, clean, figure, plt

fig, (a1, a2) = plt.subplots(1, 2, figsize=(10, 4.2), gridspec_kw={"width_ratios": [1, 1.5]})
t = np.linspace(0, 2 * math.pi, 300)
a1.plot(np.cos(t), np.sin(t), color=INK, lw=1.4)
x0 = 0.9
P = np.array([math.cos(x0), math.sin(x0)])
V = np.array([-math.sin(x0), math.cos(x0)])
a1.annotate("", xy=P, xytext=(0, 0), arrowprops=dict(arrowstyle="-", color=MUTED, lw=1.2))
a1.annotate("", xy=P + 0.7 * V, xytext=P, arrowprops=dict(arrowstyle="-|>", color=RED, lw=2, mutation_scale=14))
a1.plot(*P, "o", color=INK, ms=5)
a1.plot([P[0], P[0]], [0, P[1]], color=GREEN, lw=1, ls="--")
a1.plot([0, P[0]], [0, 0], color=BLUE, lw=1, ls="--")
a1.text(P[0] + 0.7 * V[0] - 0.35, P[1] + 0.7 * V[1] + 0.05, T("速度 (−sin x, cos x)", "velocity (−sin x, cos x)"), color=RED, fontsize=10)
a1.text(0.12, 0.08, "$x$", fontsize=12)
a1.text(P[0] + 0.05, P[1] / 2, r"$\sin x$", color=GREEN, fontsize=11)
a1.text(P[0] / 2 - 0.1, -0.15, r"$\cos x$", color=BLUE, fontsize=11)
a1.set_aspect("equal")
a1.set_xlim(-1.3, 1.5)
a1.set_ylim(-1.3, 1.5)
clean(a1)
a1.axvline(0, color=MUTED, lw=0.6, zorder=0)
a1.set_title(T("点以单位角速度转动", "A point turning at unit angular speed"), fontsize=11)
xs = np.linspace(-0.5, 2 * math.pi + 0.3, 400)
a2.plot(xs, np.sin(xs), color=GREEN, lw=2, label=r"$\sin x$")
a2.plot(xs, np.cos(xs), color=BLUE, lw=2, ls="--", label=r"$\cos x = (\sin x)'$")
for xk in (0, math.pi / 2, math.pi):
    a2.plot([xk - 0.5, xk + 0.5], [math.sin(xk) - 0.5 * math.cos(xk), math.sin(xk) + 0.5 * math.cos(xk)], color=RED, lw=1.4)
    a2.plot([xk], [math.sin(xk)], "o", color=RED, ms=4)
a2.set_xticks([0, math.pi / 2, math.pi, 3 * math.pi / 2, 2 * math.pi])
a2.set_xticklabels(["0", r"$\pi/2$", r"$\pi$", r"$3\pi/2$", r"$2\pi$"])
a2.legend(frameon=False, loc="lower left")
clean(a2)
a2.set_title(T("正弦曲线各点切线的斜率，正好画出余弦曲线", "The slopes of sin x trace out cos x"), fontsize=11)
fig.tight_layout()
figure(fig, "fig7_4_1")

fig, ax = plt.subplots(figsize=(6.0, 4.4))
xs = np.linspace(-1.2, 1.2, 300)
for a, c, name in ((2, BLUE, "$2^x$"), (math.e, RED, "$e^x$"), (3, GREEN, "$3^x$")):
    ax.plot(xs, a**xs, color=c, lw=2, label=name)
    ax.plot(xs, 1 + math.log(a) * xs, color=c, lw=1, ls="--")
ax.plot([0], [1], "o", color=INK, ms=5)
ax.set_xlim(-1.2, 1.2)
ax.set_ylim(-0.4, 3.4)
ax.legend(frameon=False, loc="upper left")
ax.text(0.45, 0.35, T("虚线：在 (0, 1) 处的切线", "dashed: tangents at (0, 1)"), color=MUTED, fontsize=10)
clean(ax)
ax.axvline(0, color=MUTED, lw=0.6, zorder=0)
ax.set_title(T("只有 eˣ 在 0 点的切线斜率恰好是 1", "Only eˣ has slope exactly 1 at 0"), fontsize=11)
fig.tight_layout()
figure(fig, "fig7_4_2")

w_inf, tau = 300.0, 0.05
t = np.linspace(0, 0.25, 300)
fig, ax = plt.subplots(figsize=(6.4, 4.0))
ax.plot(t, w_inf * (1 - np.exp(-t / tau)), color=INK, lw=2)
ax.plot([0, tau], [0, w_inf], color=RED, lw=1.5, ls="--")
ax.axhline(w_inf, color=MUTED, ls=":", lw=1)
ax.axvline(tau, color=MUTED, ls=":", lw=1)
ax.plot([tau], [w_inf * (1 - math.exp(-1))], "o", color=BLUE, ms=6)
ax.text(tau + 0.004, w_inf * (1 - math.exp(-1)) - 25, T("t = τ 时达到 63.2%", "63.2% at t = τ"), color=BLUE)
ax.text(0.012, w_inf * 0.9, T("t = 0 处的切线", "tangent at t = 0"), color=RED, ha="right")
ax.set_xlabel(T("时间 t / s", "time t / s"))
ax.set_ylabel(T("转速 ω / (rad/s)", "speed ω / (rad/s)"))
ax.set_xticks([0, tau, 0.1, 0.15, 0.2, 0.25])
ax.set_xticklabels(["0", "τ", "0.1", "0.15", "0.2", "0.25"])
clean(ax, zero=False)
fig.tight_layout()
figure(fig, "fig7_4_3")
