<?php
// Writes config.php from environment variables. Run by entrypoint.sh on every start.
$e = fn($k, $d = '') => getenv($k) !== false && getenv($k) !== '' ? getenv($k) : $d;
$wwwroot = rtrim($e('MOODLE_WWWROOT', 'http://localhost:8080'), '/');
$cfg = [
    'dbtype' => 'pgsql', 'dblibrary' => 'native',
    'dbhost' => $e('DB_HOST', 'db'), 'dbname' => $e('DB_NAME', 'moodle'),
    'dbuser' => $e('DB_USER', 'moodle'), 'dbpass' => $e('DB_PASSWORD'),
    'prefix' => 'mdl_', 'wwwroot' => $wwwroot, 'dataroot' => '/var/www/moodledata', 'admin' => 'admin',
];
$out = "<?php  // Generated by write_config.php. Do not edit; change the environment instead.\n";
$out .= "unset(\$CFG);\nglobal \$CFG;\n\$CFG = new stdClass();\n";
foreach ($cfg as $k => $v) {
    $out .= "\$CFG->{$k} = " . var_export($v, true) . ";\n";
}
$out .= "\$CFG->dboptions = ['dbpersist' => 0, 'dbport' => " . var_export($e('DB_PORT', '5432'), true) . "];\n";
$out .= "\$CFG->directorypermissions = 02777;\n";
$out .= "\$CFG->routerconfigured = true;\n";
// Behind an HTTPS reverse proxy (Nginx, cloud load balancer) Moodle must know the original scheme.
if ($e('MOODLE_SSLPROXY') === 'true') {
    $out .= "\$CFG->sslproxy = true;\n";
    // The proxy (Caddy) overwrites X-Forwarded-For with the real client address, so trust that header
    // (skip only Client-IP), and ignore the Docker network addresses of the proxy itself.
    $out .= "\$CFG->getremoteaddrconf = 1;\n";
    $out .= "\$CFG->reverseproxyignore = '10.0.0.0/8,172.16.0.0/12,192.168.0.0/16';\n";
}
// Outgoing mail. Cloud hosts often block ports 25/465/587; email services also listen on 2525.
if ($e('SMTP_HOST')) {
    $out .= "\$CFG->smtphosts = " . var_export($e('SMTP_HOST') . ':' . $e('SMTP_PORT', '2525'), true) . ";\n";
    $out .= "\$CFG->smtpsecure = " . var_export($e('SMTP_SECURE', 'tls'), true) . ";\n";
    $out .= "\$CFG->smtpauthtype = 'LOGIN';\n";
    $out .= "\$CFG->smtpuser = " . var_export($e('SMTP_USER'), true) . ";\n";
    $out .= "\$CFG->smtppass = " . var_export($e('SMTP_PASSWORD'), true) . ";\n";
}
if ($e('MOODLE_NOREPLY_EMAIL')) {
    $out .= "\$CFG->noreplyaddress = " . var_export($e('MOODLE_NOREPLY_EMAIL'), true) . ";\n";
}
if ($e('REDIS_HOST')) {
    $out .= "\$CFG->session_handler_class = '\\\\core\\\\session\\\\redis';\n";
    $out .= "\$CFG->session_redis_host = " . var_export($e('REDIS_HOST'), true) . ";\n";
}
$out .= "require_once(__DIR__ . '/lib/setup.php');\n";
file_put_contents(__DIR__ . '/config.php', $out);
