<?php
// Writes config.php from environment variables. Run by entrypoint.sh on every start.
$e = fn($k, $d = '') => getenv($k) !== false && getenv($k) !== '' ? getenv($k) : $d;
$wwwroot = rtrim($e('MOODLE_WWWROOT', 'http://localhost:8080'), '/');
$cfg = [
    'dbtype' => 'pgsql', 'dblibrary' => 'native',
    'dbhost' => $e('DB_HOST', 'db'), 'dbname' => $e('DB_NAME', 'moodle'),
    'dbuser' => $e('DB_USER', 'moodle'), 'dbpass' => $e('DB_PASSWORD'),
    'prefix' => 'mdl_', 'wwwroot' => $wwwroot, 'dataroot' => '/var/www/moodledata', 'admin' => 'admin',
];
$out = "<?php  // Generated by write_config.php. Do not edit; change the environment instead.\n";
$out .= "unset(\$CFG);\nglobal \$CFG;\n\$CFG = new stdClass();\n";
foreach ($cfg as $k => $v) {
    $out .= "\$CFG->{$k} = " . var_export($v, true) . ";\n";
}
$out .= "\$CFG->dboptions = ['dbpersist' => 0, 'dbport' => " . var_export($e('DB_PORT', '5432'), true) . "];\n";
$out .= "\$CFG->directorypermissions = 02777;\n";
$out .= "\$CFG->routerconfigured = true;\n";
// Behind an HTTPS reverse proxy (Nginx, cloud load balancer) Moodle must know the original scheme.
if ($e('MOODLE_SSLPROXY') === 'true') {
    $out .= "\$CFG->sslproxy = true;\n";
}
if ($e('REDIS_HOST')) {
    $out .= "\$CFG->session_handler_class = '\\\\core\\\\session\\\\redis';\n";
    $out .= "\$CFG->session_redis_host = " . var_export($e('REDIS_HOST'), true) . ";\n";
}
$out .= "require_once(__DIR__ . '/lib/setup.php');\n";
file_put_contents(__DIR__ . '/config.php', $out);
