"""A full lesson spec written to the benchmark: 2.1 Newton's first law and inertial frames.

Used to check every renderer against the chapter-1 layout, and as the offline (fake model) output
so local demos show what a real lesson looks like.
"""

LESSON_2_1 = {
    "title": ["牛顿第一定律与惯性参考系", "Newton’s first law and inertial frames"],
    "goal": ["理解惯性和牛顿第一定律，会判断一个参考系是不是惯性系，并用它分析 AGV 急停时货物的运动",
             "Understand inertia and Newton’s first law, tell whether a frame is inertial, and use it to analyse cargo on a braking AGV"],
    "problem": {
        "title": ["AGV 急停：货物会不会滑出去？", "AGV emergency stop: will the cargo slide off?"],
        "text": ["仓储 AGV 载着一箱货以 1.5 m/s 行驶，前方突然有人，AGV 在 0.5 s 内刹停。货箱没有固定，与车板间的静摩擦因数 μ = 0.3。货箱会不会相对车板滑动？如果滑动，会滑多远？",
                 "A warehouse AGV carries an unsecured box at 1.5 m/s and stops within 0.5 s when a person steps out. The static friction coefficient between box and deck is μ = 0.3. Will the box slide relative to the deck, and if so, how far?"],
        "given": [["初速度 v₀ = 1.5 m/s，刹车时间 0.5 s（匀减速）", "initial speed v₀ = 1.5 m/s, stops in 0.5 s (uniform deceleration)"],
                  ["静摩擦因数 μ = 0.3，动摩擦因数 μk = 0.25", "static friction μ = 0.3, kinetic friction μk = 0.25"],
                  ["货箱距车板前挡板 0.40 m", "box is 0.40 m from the front rail"]],
        "answer": ["AGV 减速度 3.0 m/s² 大于摩擦能提供的 μg ≈ 2.9 m/s²，货箱会滑动；相对车板滑动约 0.08 m，碰不到 0.40 m 外的前挡板",
                   "The AGV decelerates at 3.0 m/s², more than friction can give (μg ≈ 2.9 m/s²), so the box slides — about 0.08 m relative to the deck, well short of the rail 0.40 m ahead"],
    },
    "concept": {
        "title": ["惯性与惯性参考系", "Inertia and inertial frames"],
        "points": [["牛顿第一定律：不受力（或合力为零）的物体保持静止或匀速直线运动", "First law: with no net force an object stays at rest or moves in a straight line at constant speed"],
                   ["惯性：物体保持原有运动状态的性质，质量是惯性大小的量度", "Inertia: the tendency to keep the state of motion; mass measures it"],
                   ["惯性参考系：牛顿第一定律在其中成立的参考系；相对惯性系匀速运动的参考系也是惯性系", "Inertial frame: a frame where the first law holds; frames moving uniformly relative to it are inertial too"],
                   ["加速的车厢不是惯性系：在其中看，物体会“无缘无故”地加速", "An accelerating carriage is not inertial: objects seem to accelerate for no reason"]],
        "formula": ["ΣF = 0  ⇔  v = 常矢量（在惯性系中）", "ΣF = 0  ⇔  v = constant vector (in an inertial frame)"],
    },
    "notes": [
        {"heading": ["从亚里士多德到伽利略", "From Aristotle to Galileo"],
         "zh": "<p>亚里士多德认为“力是维持运动的原因”。伽利略用理想斜面实验指出：如果没有摩擦，小球会一直运动下去。力不是维持运动的原因，而是<strong>改变运动状态</strong>的原因。</p>",
         "en": "<p>Aristotle held that force keeps things moving. Galileo’s ideal-incline experiment showed that without friction a ball would roll on forever: force does not maintain motion, it <strong>changes</strong> it.</p>"},
        {"heading": ["牛顿第一定律与惯性", "The first law and inertia"],
         "zh": "<p>任何物体都保持静止或匀速直线运动状态，直到外力迫使它改变这种状态为止。物体保持原有运动状态的性质叫惯性，质量越大，惯性越大。</p><p>第一定律同时给出了<strong>力</strong>的定性含义：力是使物体运动状态改变的原因。</p>",
         "en": "<p>Every object stays at rest or in uniform straight-line motion until a force changes that state. This tendency is inertia; the larger the mass, the larger the inertia.</p><p>The law also tells us what a <strong>force</strong> is: whatever changes an object’s state of motion.</p>"},
        {"heading": ["惯性参考系", "Inertial frames"],
         "zh": "<p>第一定律并不是在任何参考系中都成立。在刹车的 AGV 上看，货箱没有受到向前的力，却向前滑去——这个参考系不是惯性系。能使第一定律成立的参考系叫<strong>惯性参考系</strong>。地面在大多数工程问题中可以近似看作惯性系；相对它做匀速直线运动的参考系也是惯性系。</p>",
         "en": "<p>The first law does not hold in every frame. Seen from a braking AGV, the box slides forward although nothing pushes it forward: that frame is not inertial. A frame in which the first law holds is an <strong>inertial frame</strong>. For most engineering problems the ground is close enough to inertial, and any frame moving uniformly relative to it is inertial too.</p>"},
    ],
    "example": {
        "question": ["AGV 以 a = 3.0 m/s² 减速，货箱质量 20 kg，μ = 0.3。在地面参考系中，货箱需要多大的摩擦力才能与车一起减速？静摩擦够不够？",
                     "The AGV decelerates at a = 3.0 m/s²; the box is 20 kg and μ = 0.3. In the ground frame, what friction does the box need to decelerate with the AGV? Is static friction enough?"],
        "steps": [["要与车一起减速，货箱需要 f = ma = 20 × 3.0 = 60 N", "To decelerate with the AGV the box needs f = ma = 20 × 3.0 = 60 N"],
                  ["最大静摩擦 f_max = μmg = 0.3 × 20 × 9.8 = 58.8 N", "Maximum static friction f_max = μmg = 0.3 × 20 × 9.8 = 58.8 N"],
                  ["60 N > 58.8 N，静摩擦不够，货箱相对车板向前滑动", "60 N > 58.8 N: static friction is not enough; the box slides forward on the deck"]],
        "answer": ["货箱会滑动；把减速度降到 μg ≈ 2.9 m/s² 以下就不会滑", "The box slides; keeping the deceleration below μg ≈ 2.9 m/s² prevents it"],
    },
    "animation": {
        "title": ["惯性：运动不需要力来维持", "Inertia: motion needs no force to keep going"],
        "question": ["车停了，货箱为什么还往前走？", "The AGV has stopped — why does the box keep going?"],
        "beats": [["伽利略的理想斜面：斜面越平，小球滚得越远", "Galileo’s ideal incline: the flatter the slope, the farther the ball rolls"],
                  ["没有摩擦时，小球会一直滚下去", "Without friction the ball would roll forever"],
                  ["AGV 匀速行驶，货箱和车一起运动", "The AGV cruises; the box moves with it"],
                  ["AGV 急停：地面上看，货箱保持原来的速度向前", "Emergency stop: from the ground, the box keeps its speed"],
                  ["车上看，货箱“自己”向前滑——车不是惯性系", "From the AGV the box slides forward by itself — the AGV is not an inertial frame"],
                  ["摩擦力能提供的最大减速度 μg，决定货箱滑不滑", "The largest deceleration friction can give, μg, decides whether it slides"]],
    },
    "lab": {
        "title": ["惯性与惯性参考系", "Inertia and inertial frames"],
        "robot_scene": ["机器人：AGV 急停——调节刹车减速度和摩擦因数，看货箱是否滑动、滑多远", "Robot: AGV emergency stop — set the braking and the friction, see whether and how far the box slides"],
        "life_scene": ["公交车急刹——车上站立的乘客和车外的观察者看到的运动", "Bus braking — what a standing passenger and a pedestrian see"],
        "params": [["刹车减速度 0–6 m/s²", "braking deceleration 0–6 m/s²"], ["摩擦因数 0–0.8", "friction coefficient 0–0.8"], ["观察者：地面 / 车上", "observer: ground / on board"]],
        "tasks": [["找出货箱刚好不滑动的最大减速度，与 μg 比较", "Find the largest deceleration at which the box does not slide; compare with μg"],
                  ["μ = 0.3、减速度 3.0 m/s²：读出货箱相对车板的滑动距离", "μ = 0.3, deceleration 3.0 m/s²: read how far the box slides on the deck"],
                  ["切换到“车上”观察者，说出货箱为什么看起来“自己”在动", "Switch to the on-board observer and explain why the box seems to move by itself"]],
    },
    "model": {
        "assume": ["货箱看成质点；AGV 匀减速；摩擦力不超过 μmg，滑动后为 μk·mg", "Box as a particle; uniform braking; friction at most μmg, then μk·mg once sliding"],
        "solve": ["AGV 减速度 a = 1.5/0.5 = 3.0 m/s² > μg = 2.94 m/s²，货箱滑动；滑动时货箱减速度 μk·g = 2.45 m/s²，相对车板滑动 Δx = v₀²/(2μk·g) − v₀²/(2a) ≈ 0.46 − 0.375 ≈ 0.08 m",
                  "AGV deceleration a = 1.5/0.5 = 3.0 m/s² > μg = 2.94 m/s², so the box slides; sliding, it decelerates at μk·g = 2.45 m/s² and moves Δx = v₀²/(2μk·g) − v₀²/(2a) ≈ 0.46 − 0.375 ≈ 0.08 m relative to the deck"],
        "check": ["虚拟实验“AGV 急停”：设 μ = 0.3、减速度 3.0 m/s²，读出滑动距离并与计算比较", "Lab “AGV emergency stop”: set μ = 0.3 and 3.0 m/s², read the slide and compare"],
        "improve": ["实际刹车不是匀减速，货箱也会翻倒而不只是滑动；规划刹车曲线时要把减速度限制在 μg 以下，或加固定装置", "Real braking is not uniform, and a tall box may tip rather than slide; limit the deceleration below μg or secure the load"],
    },
    "everyday": {"text": ["公交车急刹，站着的乘客向前倾。以车为参考系，是什么“力”推了乘客？", "When a bus brakes hard, standing passengers lurch forward. In the bus frame, what ‘force’ pushed them?"],
                 "answer": ["没有真实的力推他：乘客由于惯性保持原速度，是车在减速；车不是惯性系", "Nothing pushed them: by inertia they keep their speed while the bus slows; the bus is not an inertial frame"]},
    "summary": [["力不是维持运动的原因，而是改变运动状态的原因", "Force changes motion; it does not maintain it"],
                ["惯性的大小由质量量度", "Mass measures inertia"],
                ["牛顿定律只在惯性系中成立；加速的车厢不是惯性系", "Newton’s laws hold in inertial frames; an accelerating carriage is not one"]],
    "self_check": [["匀速上升的电梯是不是惯性系？正在加速的呢？", "Is an elevator rising at constant speed an inertial frame? And one that is speeding up?"],
                   ["为什么说质量是惯性大小的量度？举一个例子", "Why is mass a measure of inertia? Give an example"]],
}

GUIDE_PLAN_2_1 = {
    "guide": {
        "goal": [["理解惯性和牛顿第一定律", "Understand inertia and Newton’s first law"],
                 ["学会判断参考系是否为惯性系", "Tell whether a frame is inertial"],
                 ["用摩擦力的上限 μmg 分析 AGV 急停时货物是否滑动", "Use the friction limit μmg to decide whether cargo slides when an AGV stops"]],
        "theory": [["在地面（惯性系）中，货箱只受摩擦力，最大为 μmg，能提供的最大减速度为 μg。", "In the ground frame the box feels only friction, at most μmg, so its largest deceleration is μg."],
                   ["若 AGV 减速度 a > μg，货箱相对车板滑动，此后受动摩擦 μk·mg。", "If the AGV decelerates at a > μg the box slides and feels kinetic friction μk·mg."]],
        "env": [{"item": ["场景", "Scene"], "range": ["机器人：AGV 急停；公交车急刹", "Robot: AGV emergency stop; bus braking"]},
                {"item": ["刹车减速度", "Braking"], "range": ["0 – 6 m/s²", "0 – 6 m/s²"]},
                {"item": ["摩擦因数", "Friction"], "range": ["0 – 0.8", "0 – 0.8"]}],
        "steps": [["选“AGV 急停”，μ = 0.3，减速度从 1.0 m/s² 起逐步增大，找出货箱开始滑动的减速度，填表 1。", "Choose “AGV emergency stop”, μ = 0.3; raise the deceleration from 1.0 m/s² until the box starts to slide; fill in Table 1."],
                  ["μ 改为 0.2、0.5 重复。", "Repeat with μ = 0.2 and 0.5."],
                  ["μ = 0.3、减速度 3.0 m/s²，读出滑动距离，填表 2。", "With μ = 0.3 and 3.0 m/s², read the slide distance; fill in Table 2."],
                  ["切换“车上”观察者，描述货箱的运动。", "Switch to the on-board observer and describe the box’s motion."]],
        "tables": [{"caption": ["表 1  临界减速度", "Table 1  Critical deceleration"], "headers": ["μ", "临界减速度 m/s²（测）", "μg m/s²（算）"],
                    "rows": [["0.2", "", ""], ["0.3", "", ""], ["0.5", "", ""]]},
                   {"caption": ["表 2  滑动距离（μ = 0.3）", "Table 2  Slide distance (μ = 0.3)"], "headers": ["减速度 m/s²", "滑动距离 m（测）", "滑动距离 m（算）"],
                    "rows": [["3.0", "", ""], ["4.0", "", ""]]}],
        "cautions": [["读数在货箱停下后出现。", "Readings appear after the box stops."]],
        "questions": [["临界减速度为什么与货箱质量无关？", "Why does the critical deceleration not depend on the box’s mass?"],
                      ["在车上观察者看来，货箱“自己”向前滑，这与牛顿第一定律矛盾吗？", "To the on-board observer the box slides by itself. Does this contradict the first law?"]],
        "problem_question": ["AGV 以 1.5 m/s 行驶，0.5 s 内刹停，μ = 0.3。(1) 货箱会不会滑动？(2) 滑多远？(3) 怎样规划刹车才能让货箱不滑？",
                             "An AGV at 1.5 m/s stops in 0.5 s, μ = 0.3. (1) Does the box slide? (2) How far? (3) How should braking be planned so it does not?"],
    },
    "plan": {"audience": "工科一年级", "hours": "2 学时", "method": "问题驱动 + 动画 + 虚拟实验",
             "objectives": {"knowledge": "理解惯性和牛顿第一定律，掌握惯性参考系的概念。", "ability": "能用摩擦力上限分析急停时物体是否滑动。",
                            "literacy": "体会从理想实验到物理定律的思维方法。"},
             "key": "牛顿第一定律；惯性参考系。", "difficult": "在非惯性系中如何理解物体“自己”的运动。",
             "process": [{"phase": "导入", "minutes": 10, "content": "AGV 急停视频：货箱会不会滑出去？", "activity": "学生预测并投票"},
                         {"phase": "新课", "minutes": 30, "content": "伽利略理想斜面；牛顿第一定律；惯性与质量", "activity": "讲授 + 板书"},
                         {"phase": "动画", "minutes": 10, "content": "惯性：运动不需要力来维持", "activity": "播放、暂停提问"},
                         {"phase": "实验", "minutes": 20, "content": "虚拟实验：找临界减速度", "activity": "课堂演示，学生记录"},
                         {"phase": "建模", "minutes": 15, "content": "五步解决 AGV 急停问题", "activity": "师生共同完成"},
                         {"phase": "小结", "minutes": 5, "content": "惯性系与非惯性系", "activity": "布置练习和实验报告"}],
             "board": "左：第一定律与惯性；中：惯性系判断；右：AGV 急停五步建模。", "homework": "练习 2.1；虚拟实验任务 1–3；实验报告。", "reflection": ""},
}
